title: Fritzing Parts Graphics-Python Scripts
description: Python scripts mainly used for renumbering connectors
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
footer:
  copyright: "Website maintained by RAPTOR7762, Python scripts maintained by Peter Van Epp
